version: '3.8'
services:
  postgres_test:
    image: postgres:15
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: testdb
    ports:
      - "55432:5432"
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U test -d testdb"]
      interval: 5s
      timeout: 5s
      retries: 5


