[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "aiser-authentication-service"
version = "0.1"
description = "AIser Authentication Service"
authors = [{ name = "Kimseng Duong", email = "kimseng.duong@dataticon.com" }]
requires-python = ">=3.8"
dependencies = [
    "fastapi>=0.104.1",
    "uvicorn>=0.24.0",
    "alembic>=1.13.0",
    "SQLAlchemy>=2.0.23",
    "asyncpg>=0.30.0",
    "pydantic>=2.10.4",
    "pydantic-settings>=2.7.0",
    "python-jose>=3.3.0",
    "psycopg2-binary>=2.9.9",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.scripts]
fastrun = "app.cli.main:fastrun"

[tool.setuptools.packages.find]
where = ["src"]      # If your packages are in a `src` directory
exclude = ["tests*"] # Exclude test packages
