[tool.poetry]
name = "aiser-world-auth"
version = "0.1.0"
description = "Aiser World Authentication Service"
authors = ["BigStack Analytics <info@bigstack-analytics.com>"]
license = "Commercial"
readme = "README.md"
packages = [{include = "app", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.104.1"
uvicorn = {extras = ["standard"], version = "^0.24.0"}
alembic = "^1.13.0"
asyncpg = "^0.30.0"
psycopg2-binary = "^2.9.9"
sqlalchemy = "^2.0.23"
cryptography = "^41.0.7"
passlib = "^1.7.4"
python-jose = "^3.3.0"
email-validator = "^2.2.0"
pydantic = "^2.10.4"
pydantic-settings = "^2.7.0"
colorama = "^0.4.6"
python-dotenv = "^1.0.0"
pandas = "^2.2.3"
python-multipart = "^0.0.20"
pillow = "^10.0.0"
emails = "^0.6"
jinja2 = "^3.1.5"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-asyncio = "^0.21.0"
black = "^23.0.0"
isort = "^5.12.0"
flake8 = "^6.0.0"
mypy = "^1.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py311']

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true