-- Fix user passwords by updating them with correct passlib format pbkdf2_sha256 hashes
-- This script uses the exact format generated by the passlib library

-- Update admin user password
UPDATE users 
SET password = '$pbkdf2-sha256$29000$OWUyNWEyNTg4ZmNlZTdkMjFlYTE1ZmIxYTYzZDUxMzU$oXfQRURC44r434pgnf4Ov/tbSOcNkLVlotNvxxY/Qrs'
WHERE username = 'admin';

-- Update user password  
UPDATE users 
SET password = '$pbkdf2-sha256$29000$OWUyNWEyNTg4ZmNlZTdkMjFlYTE1ZmIxYTYzZDUxMzU$uhZCt30qw0Pus6iWlLdOCP/OX.Eb8ZyFMddaZ2OXRTi0'
WHERE username = 'user';

-- Update analyst password
UPDATE users 
SET password = '$pbkdf2-sha256$29000$OWUyNWEyNTg4ZmNlZTdkMjFlYTE1ZmIxYTYzZDUxMzU$UjJRcrI2p5wCKacoKVZ0kO8L2sZmC6ccSHF0MuPkvTMg'
WHERE username = 'analyst';

-- Update testuser password
UPDATE users 
SET password = '$pbkdf2-sha256$29000$OWUyNWEyNTg4ZmNlZTdkMjFlYTE1ZmIxYTYzZDUxMzU$jhdwHgSGNpkLq7qyhh55qMHPJVQCzLL.ZdSgx37JBHAE'
WHERE username = 'testuser';

-- Verify the updates
SELECT username, 
       CASE 
           WHEN password LIKE '$pbkdf2-sha256$%' THEN 'CORRECT_PASSLIB_HASH'
           ELSE 'INCORRECT_HASH'
       END as hash_status,
       LENGTH(password) as hash_length
FROM users;

-- Commit the changes
COMMIT;
