[tool.poetry]
name = "aiser-world-chat2chart"
version = "0.1.0"
description = "Aiser World Chat2Chart AI Engine"
authors = ["BigStack Analytics <info@bigstack-analytics.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "app"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.104.1"
uvicorn = {extras = ["standard"], version = "^0.24.0"}
alembic = "^1.13.0"
asyncpg = "^0.30.0"
psycopg2-binary = "^2.9.9"
sqlalchemy = "^2.0.23"
cryptography = "^41.0.7"
passlib = "^1.7.4"
python-jose = "^3.3.0"
email-validator = "^2.2.0"
pydantic = "^2.10.4"
pydantic-settings = "^2.7.0"
openai = "^1.59.7"
litellm = "^1.55.0"
boto3 = "^1.26.137"
colorama = "^0.4.6"
pandas = "^2.2.3"
numpy = "^1.24.0"
pillow = "^10.0.0"
redis = "^5.0.0"
python-dotenv = "^1.0.0"
python-multipart = "^0.0.20"
openpyxl = "^3.1.2"
xlrd = "^2.0.1"
tabula-py = "^2.8.2"
pyarrow = "^14.0.2"
fastparquet = "^2024.2.0"
python-snappy = "^0.6.1"
chardet = "^5.2.0"
# Database Drivers
pymysql = "^1.1.0"
mysql-connector-python = "^8.2.0"
pyodbc = "^5.0.1"
cx-Oracle = "^8.3.0"
pymongo = "^4.6.0"
elasticsearch = "^8.11.0"
influxdb-client = "^1.38.0"
neo4j = "^5.15.0"
# Data Warehouse Drivers
snowflake-connector-python = "^3.6.0"
google-cloud-bigquery = "^3.13.0"
redshift-connector = "^2.0.908"
databricks-sql-connector = "^3.0.0"
databricks-connect = "^14.0.0"
clickhouse-connect = "^0.7.0"
# Additional utilities
sqlalchemy-utils = "^0.41.1"
PyYAML = "^6.0.1"
# LangChain dependencies for NL2SQL agent
langchain = "^0.3.0"
langchain-core = "^0.3.0"
langchain-community = "^0.3.0"
sqlparse = "^0.5.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-asyncio = "^0.21.0"
black = "^23.0.0"
isort = "^5.12.0"
flake8 = "^6.0.0"
mypy = "^1.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py311']

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true