name: CI - Migrations Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  migrations:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: aiser_world_ci
          POSTGRES_USER: aiser
          POSTGRES_PASSWORD: aiser_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U aiser -d aiser_world_ci" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r packages/chat2chart/server/requirements.txt

      - name: Run Alembic migrations against clean DB
        env:
          POSTGRES_DB: aiser_world_ci
          POSTGRES_USER: aiser
          POSTGRES_PASSWORD: aiser_password
          POSTGRES_SERVER: localhost
          POSTGRES_PORT: 5432
        run: |
          cd packages/chat2chart/server
          alembic -c alembic.ini upgrade head


