"""alignment

Revision ID: 071685cb1d9c
Revises: initial_four_tables
Create Date: 2026-01-08 02:37:51.838885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '071685cb1d9c'
down_revision: Union[str, None] = 'initial_four_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_conversation_created_at'), table_name='conversation')
    op.drop_index(op.f('idx_conversation_user_id'), table_name='conversation')
    op.create_index(op.f('ix_conversation_id'), 'conversation', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_user_id'), 'conversation', ['user_id'], unique=False)
    op.create_index(op.f('ix_data_sources_user_id'), 'data_sources', ['user_id'], unique=False)
    op.execute("""
        ALTER TABLE file_storage 
        ALTER COLUMN user_id TYPE uuid USING user_id::uuid
    """)
    op.alter_column('message', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('message', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_index(op.f('ix_message_id'), 'message', ['id'], unique=False)
    op.alter_column('file_storage', 'is_active',
            existing_type=sa.Boolean(),
            server_default=sa.text("true"),
            existing_nullable=True)
    op.alter_column('data_sources', 'is_active',
        existing_type=sa.Boolean(),
        server_default=sa.text("true"),
        existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_id'), table_name='message')
    op.alter_column('message', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('message', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.execute("""
        ALTER TABLE file_storage 
        ALTER COLUMN user_id TYPE varchar USING user_id::text
    """)
    op.drop_index(op.f('ix_data_sources_user_id'), table_name='data_sources')
    op.drop_index(op.f('ix_conversation_user_id'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_id'), table_name='conversation')
    op.create_index(op.f('idx_conversation_user_id'), 'conversation', ['user_id'], unique=False)
    op.create_index(op.f('idx_conversation_created_at'), 'conversation', ['created_at'], unique=False)
    op.alter_column('file_storage', 'is_active',
            existing_type=sa.Boolean(),
            server_default=None,
            existing_nullable=True)
    op.alter_column('data_sources', 'is_active',
        existing_type=sa.Boolean(),
        server_default=None,
        existing_nullable=True)
    # ### end Alembic commands ###