"""tweak

Revision ID: 801091543375
Revises: 071685cb1d9c
Create Date: 2026-01-08 02:53:35.629856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '801091543375'
down_revision: Union[str, None] = '071685cb1d9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE data_sources 
        ALTER COLUMN user_id TYPE uuid USING user_id::uuid
    """)
    op.alter_column('data_sources', 'user_id',
            existing_type=sa.UUID(),
            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_sources', 'user_id',
            existing_type=sa.UUID(),
            nullable=True)
    op.execute("""
        ALTER TABLE data_sources 
        ALTER COLUMN user_id TYPE varchar USING user_id::text
    """)
    # ### end Alembic commands ###