// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/ai-analytics" | "/auth-debug" | "/auth-test" | "/billing" | "/charts" | "/chat" | "/dark-mode-validation" | "/dash-studio" | "/dash-studio/test-charts" | "/dashboards" | "/data" | "/embedded/chart/[slug]" | "/login" | "/logout" | "/projects" | "/settings" | "/settings/general" | "/settings/notifications" | "/settings/profile" | "/settings/security" | "/simple-auth-test" | "/storage" | "/team" | "/test-auth" | "/test-chat" | "/test-dark-mode" | "/test-dash-studio" | "/test-design-system" | "/tester/charts" | "/tester/loading" | "/tester/upload"
type AppRouteHandlerRoutes = "/api/ai/chat/analyze" | "/api/ai/chat/stream" | "/api/conversations" | "/api/conversations/[id]"
type PageRoutes = "/_error"
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/_error": {}
  "/ai-analytics": {}
  "/api/ai/chat/analyze": {}
  "/api/ai/chat/stream": {}
  "/api/conversations": {}
  "/api/conversations/[id]": { "id": string; }
  "/auth-debug": {}
  "/auth-test": {}
  "/billing": {}
  "/charts": {}
  "/chat": {}
  "/dark-mode-validation": {}
  "/dash-studio": {}
  "/dash-studio/test-charts": {}
  "/dashboards": {}
  "/data": {}
  "/embedded/chart/[slug]": { "slug": string; }
  "/login": {}
  "/logout": {}
  "/projects": {}
  "/settings": {}
  "/settings/general": {}
  "/settings/notifications": {}
  "/settings/profile": {}
  "/settings/security": {}
  "/simple-auth-test": {}
  "/storage": {}
  "/team": {}
  "/test-auth": {}
  "/test-chat": {}
  "/test-dark-mode": {}
  "/test-dash-studio": {}
  "/test-design-system": {}
  "/tester/charts": {}
  "/tester/loading": {}
  "/tester/upload": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
